Vagrant.configure("2") do |config|
  config.vm.box = "stobias123/vagrant_developer_box"

  ## Mount the user repos dir
  if Vagrant::Util::Platform.windows?
     target_path = ENV['USERPROFILE'].gsub(/\\/,'/').gsub(/[[:alpha:]]{1}:/){|s|'/' + s.downcase.sub(':', '')}
    config.vm.synced_folder "#{ENV['USERPROFILE']}/repos", "/vagrant/repos"
  else
    config.vm.synced_folder "#{ENV['HOME']}/repos", "vagrant/repos"
  end
end
