Vagrant.configure("2") do |config|
  config.vm.box = "stobias123/vagrant_developer_box"
  config.vm.box_version = "0.07"

  ## Mount the user repos dir
  config.vm.synced_folder '.', '/vagrant/repos'
  config.vm.box_download_insecure = true
end
